# Generated by Django 3.1.5 on 2021-01-11 06:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('accmanage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guest',
            name='customuser_ptr',
        ),
        migrations.DeleteModel(
            name='admina',
        ),
        migrations.AddField(
            model_name='customuser',
            name='Age',
            field=models.IntegerField(default=18, validators=[django.core.validators.MinValueValidator(18)]),
        ),
        migrations.DeleteModel(
            name='guest',
        ),
        migrations.CreateModel(
            name='guest',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accmanage.customuser',),
        ),
    ]
