# Generated by Django 3.1.5 on 2021-01-11 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accmanage', '0002_auto_20210111_0819'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='Age',
        ),
    ]
