# Generated by Django 3.1.5 on 2021-01-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accmanage', '0003_remove_customuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='img',
            field=models.ImageField(default='202-2026524_person-icon-default-user-icon-png.png', upload_to='static/images/'),
        ),
    ]
