# Generated by Django 3.1.5 on 2021-01-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accmanage', '0006_auto_20210112_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='creditcard_ED',
            field=models.DateField(default=None),
        ),
        migrations.AddField(
            model_name='customuser',
            name='creditcard_cvv',
            field=models.CharField(default='', max_length=3),
        ),
    ]
