# Generated by Django 3.1.5 on 2021-01-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accmanage', '0008_auto_20210113_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='creditcard_ED',
            field=models.DateTimeField(blank=True),
        ),
    ]
