# Generated by Django 3.1.5 on 2021-01-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accmanage', '0010_auto_20210113_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='creditcard_ED',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
