# Generated by Django 3.1.5 on 2021-01-12 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accmanage', '0011_auto_20210113_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='creditcard_ED',
            field=models.DateField(blank=True),
        ),
    ]
