# Generated by Django 3.1.5 on 2021-01-12 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accmanage', '0013_auto_20210113_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='creditcard_ED',
            field=models.DateField(blank=True, default='02/03/2023'),
        ),
    ]
