# Generated by Django 3.1.5 on 2021-01-12 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accmanage', '0014_auto_20210113_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='creditcard_ED',
            field=models.DateField(blank=True, default=2006),
        ),
    ]
