# Generated by Django 3.1.5 on 2021-01-12 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accmanage', '0016_auto_20210113_0048'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
