# Generated by Django 3.1.5 on 2021-01-13 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accmanage', '0018_auto_20210113_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='type',
            field=models.CharField(choices=[('guest', 'Guest'), ('admina', 'Admina'), ('manager', 'Manager'), ('staff', 'Staff'), ('receptionist', 'Receptionist')], max_length=50, verbose_name='Type'),
        ),
    ]
