# Generated by Django 3.1.5 on 2021-01-13 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accmanage', '0020_auto_20210113_0227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='creditcard_ED',
            field=models.CharField(blank=True, default='ex: 03/24', max_length=5),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='creditcard_cvv',
            field=models.CharField(blank=True, default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='userage',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='usercreditcard',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='userphone',
            field=models.CharField(blank=True, default='', max_length=14),
        ),
    ]
