# Generated by Django 3.1.5 on 2021-01-11 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='rooms')),
                ('Name', models.CharField(default='new_hotel', max_length=50, verbose_name='Name')),
                ('Location', models.CharField(max_length=50, verbose_name='Location')),
            ],
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Room_ID', models.CharField(default=' ', max_length=15, verbose_name='ID')),
                ('view', models.CharField(choices=[('Pool View', 'Pool View'), ('Sea View', 'Sea View')], max_length=50, verbose_name='View')),
                ('wifi', models.BooleanField(default=False)),
                ('AC', models.BooleanField(default=False)),
                ('TV', models.BooleanField(default=False)),
                ('kitchen', models.BooleanField(default=False)),
                ('kettle', models.BooleanField(default=False)),
                ('MW', models.BooleanField(default=False)),
                ('MB', models.BooleanField(default=False)),
                ('bath', models.BooleanField(default=False)),
                ('room_type', models.IntegerField(choices=[(1, 'One Bed'), (2, 'Two Beds'), (3, 'Three Beds')], default=1)),
                ('Room_Img', models.ImageField(upload_to='rooms')),
                ('Hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roommanage.hotel')),
            ],
        ),
    ]
