# Generated by Django 3.1.5 on 2021-01-14 03:39

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('roommanage', '0002_auto_20210113_1057'),
    ]

    operations = [
        migrations.CreateModel(
            name='reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrivedate', models.DateField(default=datetime.datetime(2021, 1, 14, 5, 39, 0, 324472))),
                ('leavedate', models.DateField(default=datetime.datetime(2021, 1, 16, 5, 39, 0, 324472))),
                ('guestid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('roomid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roommanage.room')),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default='new_service', max_length=50, verbose_name='Name')),
                ('price', models.IntegerField(default=20)),
                ('description', models.CharField(default='', max_length=100, verbose_name='description')),
            ],
        ),
        migrations.DeleteModel(
            name='currenthotel',
        ),
    ]
