# Generated by Django 3.1.5 on 2021-01-14 05:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accmanage', '0023_auto_20210113_0411'),
        ('roommanage', '0003_auto_20210114_0539'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='serviceid',
            field=models.ManyToManyField(to='roommanage.service'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='arrivedate',
            field=models.DateField(default=datetime.datetime(2021, 1, 14, 7, 0, 33, 525148)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='guestid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accmanage.guest'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='leavedate',
            field=models.DateField(default=datetime.datetime(2021, 1, 16, 7, 0, 33, 525148)),
        ),
    ]
