# Generated by Django 3.1.5 on 2021-01-14 07:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanage', '0006_auto_20210114_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='arrivedate',
            field=models.DateField(default=datetime.datetime(2021, 1, 14, 9, 17, 50, 848125)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='leavedate',
            field=models.DateField(default=datetime.datetime(2021, 1, 16, 9, 17, 50, 848125)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='roomid',
            field=models.CharField(default='2', max_length=5),
        ),
    ]
