# Generated by Django 3.1.5 on 2021-01-14 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roommanage', '0010_auto_20210114_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='arrivedate',
            field=models.DateField(default=datetime.datetime(2021, 1, 14, 12, 21, 44, 636354)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='leavedate',
            field=models.DateField(default=datetime.datetime(2021, 1, 16, 12, 21, 44, 636354)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='serviceid',
            field=models.ManyToManyField(blank=True, to='roommanage.service'),
        ),
    ]
